"""
Static stock universe for instant search — no API calls needed.
US: ~500 stocks (S&P 500 + popular NASDAQ)
IN: ~500 NSE-listed stocks
CRYPTO: major coins
"""

US_STOCKS = [
    # Mega-cap Tech
    ("AAPL", "Apple Inc."),
    ("MSFT", "Microsoft Corporation"),
    ("GOOGL", "Alphabet Inc. (Class A)"),
    ("GOOG", "Alphabet Inc. (Class C)"),
    ("AMZN", "Amazon.com Inc."),
    ("NVDA", "NVIDIA Corporation"),
    ("META", "Meta Platforms Inc."),
    ("TSLA", "Tesla Inc."),
    ("AVGO", "Broadcom Inc."),
    ("ORCL", "Oracle Corporation"),
    ("AMD", "Advanced Micro Devices Inc."),
    ("INTC", "Intel Corporation"),
    ("QCOM", "Qualcomm Inc."),
    ("TXN", "Texas Instruments Inc."),
    ("MU", "Micron Technology Inc."),
    ("AMAT", "Applied Materials Inc."),
    ("LRCX", "Lam Research Corporation"),
    ("KLAC", "KLA Corporation"),
    ("MRVL", "Marvell Technology Inc."),
    ("NXPI", "NXP Semiconductors NV"),
    ("ON", "ON Semiconductor Corporation"),
    ("STX", "Seagate Technology Holdings"),
    ("WDC", "Western Digital Corporation"),
    ("SNPS", "Synopsys Inc."),
    ("CDNS", "Cadence Design Systems Inc."),
    ("ADBE", "Adobe Inc."),
    ("CRM", "Salesforce Inc."),
    ("NOW", "ServiceNow Inc."),
    ("INTU", "Intuit Inc."),
    ("PANW", "Palo Alto Networks Inc."),
    ("CRWD", "CrowdStrike Holdings Inc."),
    ("FTNT", "Fortinet Inc."),
    ("OKTA", "Okta Inc."),
    ("ZS", "Zscaler Inc."),
    ("NET", "Cloudflare Inc."),
    ("DDOG", "Datadog Inc."),
    ("MDB", "MongoDB Inc."),
    ("SNOW", "Snowflake Inc."),
    ("PLTR", "Palantir Technologies Inc."),
    ("UBER", "Uber Technologies Inc."),
    ("LYFT", "Lyft Inc."),
    ("ABNB", "Airbnb Inc."),
    ("DASH", "DoorDash Inc."),
    ("RBLX", "Roblox Corporation"),
    ("U", "Unity Software Inc."),
    ("SPOT", "Spotify Technology SA"),
    ("NFLX", "Netflix Inc."),
    ("DIS", "The Walt Disney Company"),
    ("CMCSA", "Comcast Corporation"),
    ("WBD", "Warner Bros. Discovery Inc."),
    ("PARA", "Paramount Global"),
    # Financials
    ("JPM", "JPMorgan Chase & Co."),
    ("BAC", "Bank of America Corporation"),
    ("WFC", "Wells Fargo & Company"),
    ("GS", "The Goldman Sachs Group Inc."),
    ("MS", "Morgan Stanley"),
    ("C", "Citigroup Inc."),
    ("BLK", "BlackRock Inc."),
    ("SCHW", "Charles Schwab Corporation"),
    ("AXP", "American Express Company"),
    ("V", "Visa Inc."),
    ("MA", "Mastercard Incorporated"),
    ("PYPL", "PayPal Holdings Inc."),
    ("SQ", "Block Inc."),
    ("COF", "Capital One Financial Corp."),
    ("USB", "U.S. Bancorp"),
    ("PNC", "PNC Financial Services Group"),
    ("TFC", "Truist Financial Corporation"),
    ("BK", "Bank of New York Mellon Corp."),
    ("STT", "State Street Corporation"),
    ("ICE", "Intercontinental Exchange Inc."),
    ("CME", "CME Group Inc."),
    ("CBOE", "Cboe Global Markets Inc."),
    ("NDAQ", "Nasdaq Inc."),
    ("SPGI", "S&P Global Inc."),
    ("MCO", "Moody's Corporation"),
    ("AON", "Aon plc"),
    ("MMC", "Marsh & McLennan Companies"),
    ("MET", "MetLife Inc."),
    ("PRU", "Prudential Financial Inc."),
    ("AFL", "Aflac Incorporated"),
    ("AIG", "American International Group"),
    ("ALL", "Allstate Corporation"),
    ("TRV", "The Travelers Companies"),
    ("PGR", "Progressive Corporation"),
    ("HIG", "Hartford Financial Services"),
    # Healthcare
    ("JNJ", "Johnson & Johnson"),
    ("UNH", "UnitedHealth Group Inc."),
    ("PFE", "Pfizer Inc."),
    ("MRK", "Merck & Co. Inc."),
    ("ABBV", "AbbVie Inc."),
    ("ABT", "Abbott Laboratories"),
    ("TMO", "Thermo Fisher Scientific Inc."),
    ("DHR", "Danaher Corporation"),
    ("BMY", "Bristol-Myers Squibb Company"),
    ("AMGN", "Amgen Inc."),
    ("GILD", "Gilead Sciences Inc."),
    ("BIIB", "Biogen Inc."),
    ("REGN", "Regeneron Pharmaceuticals Inc."),
    ("VRTX", "Vertex Pharmaceuticals Inc."),
    ("MRNA", "Moderna Inc."),
    ("BNTX", "BioNTech SE"),
    ("CVS", "CVS Health Corporation"),
    ("CI", "Cigna Group"),
    ("HUM", "Humana Inc."),
    ("CNC", "Centene Corporation"),
    ("ELV", "Elevance Health Inc."),
    ("MDT", "Medtronic plc"),
    ("SYK", "Stryker Corporation"),
    ("BSX", "Boston Scientific Corporation"),
    ("EW", "Edwards Lifesciences Corp."),
    ("ISRG", "Intuitive Surgical Inc."),
    ("ZBH", "Zimmer Biomet Holdings Inc."),
    ("BAX", "Baxter International Inc."),
    ("BDX", "Becton Dickinson and Company"),
    ("IQV", "IQVIA Holdings Inc."),
    ("A", "Agilent Technologies Inc."),
    ("IDXX", "IDEXX Laboratories Inc."),
    ("MTD", "Mettler-Toledo International"),
    ("WAT", "Waters Corporation"),
    # Consumer
    ("AMZN", "Amazon.com Inc."),
    ("WMT", "Walmart Inc."),
    ("TGT", "Target Corporation"),
    ("COST", "Costco Wholesale Corporation"),
    ("HD", "The Home Depot Inc."),
    ("LOW", "Lowe's Companies Inc."),
    ("NKE", "NIKE Inc."),
    ("SBUX", "Starbucks Corporation"),
    ("MCD", "McDonald's Corporation"),
    ("CMG", "Chipotle Mexican Grill Inc."),
    ("YUM", "Yum! Brands Inc."),
    ("QSR", "Restaurant Brands International"),
    ("DPZ", "Domino's Pizza Inc."),
    ("DKNG", "DraftKings Inc."),
    ("MGM", "MGM Resorts International"),
    ("LVS", "Las Vegas Sands Corp."),
    ("WYNN", "Wynn Resorts Limited"),
    ("MAR", "Marriott International Inc."),
    ("HLT", "Hilton Worldwide Holdings Inc."),
    ("H", "Hyatt Hotels Corporation"),
    ("CCL", "Carnival Corporation & plc"),
    ("RCL", "Royal Caribbean Cruises Ltd."),
    ("NCLH", "Norwegian Cruise Line Holdings"),
    ("BKNG", "Booking Holdings Inc."),
    ("EXPE", "Expedia Group Inc."),
    ("TRIP", "TripAdvisor Inc."),
    ("KO", "The Coca-Cola Company"),
    ("PEP", "PepsiCo Inc."),
    ("MNST", "Monster Beverage Corporation"),
    ("STZ", "Constellation Brands Inc."),
    ("BUD", "Anheuser-Busch InBev SA/NV"),
    ("TAP", "Molson Coors Beverage Company"),
    ("SAM", "Boston Beer Company Inc."),
    ("PG", "Procter & Gamble Company"),
    ("CL", "Colgate-Palmolive Company"),
    ("KMB", "Kimberly-Clark Corporation"),
    ("EL", "Estee Lauder Companies Inc."),
    ("ULTA", "Ulta Beauty Inc."),
    ("LULU", "Lululemon Athletica Inc."),
    ("VFC", "VF Corporation"),
    ("PVH", "PVH Corp."),
    ("RL", "Ralph Lauren Corporation"),
    ("TPR", "Tapestry Inc."),
    ("KR", "The Kroger Co."),
    ("ACI", "Albertsons Companies Inc."),
    ("SFM", "Sprouts Farmers Market Inc."),
    ("WBEV", "Whole Earth Brands Inc."),
    ("GIS", "General Mills Inc."),
    ("K", "Kellanova"),
    ("CPB", "Campbell Soup Company"),
    ("HRL", "Hormel Foods Corporation"),
    ("MKC", "McCormick & Company Inc."),
    ("SJM", "J.M. Smucker Company"),
    ("CAG", "Conagra Brands Inc."),
    ("HSY", "Hershey Company"),
    ("MDLZ", "Mondelez International Inc."),
    ("CL", "Colgate-Palmolive Company"),
    # Energy
    ("XOM", "Exxon Mobil Corporation"),
    ("CVX", "Chevron Corporation"),
    ("COP", "ConocoPhillips"),
    ("EOG", "EOG Resources Inc."),
    ("SLB", "Schlumberger Limited"),
    ("HAL", "Halliburton Company"),
    ("BKR", "Baker Hughes Company"),
    ("PSX", "Phillips 66"),
    ("VLO", "Valero Energy Corporation"),
    ("MPC", "Marathon Petroleum Corporation"),
    ("PXD", "Pioneer Natural Resources Co."),
    ("DVN", "Devon Energy Corporation"),
    ("FANG", "Diamondback Energy Inc."),
    ("MRO", "Marathon Oil Corporation"),
    ("APA", "APA Corporation"),
    ("OXY", "Occidental Petroleum Corp."),
    ("HES", "Hess Corporation"),
    ("KMI", "Kinder Morgan Inc."),
    ("WMB", "Williams Companies Inc."),
    ("ET", "Energy Transfer LP"),
    ("EPD", "Enterprise Products Partners"),
    ("MPLX", "MPLX LP"),
    ("LNG", "Cheniere Energy Inc."),
    ("AR", "Antero Resources Corporation"),
    ("RRC", "Range Resources Corporation"),
    # Industrials
    ("BA", "Boeing Company"),
    ("RTX", "RTX Corporation"),
    ("LMT", "Lockheed Martin Corporation"),
    ("NOC", "Northrop Grumman Corporation"),
    ("GD", "General Dynamics Corporation"),
    ("L3HT", "L3Harris Technologies Inc."),
    ("HII", "Huntington Ingalls Industries"),
    ("GE", "GE Aerospace"),
    ("HON", "Honeywell International Inc."),
    ("MMM", "3M Company"),
    ("CAT", "Caterpillar Inc."),
    ("DE", "Deere & Company"),
    ("EMR", "Emerson Electric Co."),
    ("ETN", "Eaton Corporation plc"),
    ("PH", "Parker-Hannifin Corporation"),
    ("ROK", "Rockwell Automation Inc."),
    ("CMI", "Cummins Inc."),
    ("PCAR", "PACCAR Inc."),
    ("WM", "Waste Management Inc."),
    ("RSG", "Republic Services Inc."),
    ("FDX", "FedEx Corporation"),
    ("UPS", "United Parcel Service Inc."),
    ("DAL", "Delta Air Lines Inc."),
    ("UAL", "United Airlines Holdings Inc."),
    ("AAL", "American Airlines Group Inc."),
    ("LUV", "Southwest Airlines Co."),
    ("ALK", "Alaska Air Group Inc."),
    ("JBLU", "JetBlue Airways Corporation"),
    ("CSX", "CSX Corporation"),
    ("NSC", "Norfolk Southern Corporation"),
    ("UNP", "Union Pacific Corporation"),
    ("CP", "Canadian Pacific Kansas City"),
    ("CNI", "Canadian National Railway Co."),
    ("URI", "United Rentals Inc."),
    ("FAST", "Fastenal Company"),
    ("GWW", "W.W. Grainger Inc."),
    ("MSC", "MSC Industrial Direct Co."),
    ("XYL", "Xylem Inc."),
    ("CARR", "Carrier Global Corporation"),
    ("OTIS", "Otis Worldwide Corporation"),
    ("TT", "Trane Technologies plc"),
    ("JCI", "Johnson Controls International"),
    ("IR", "Ingersoll Rand Inc."),
    ("GNRC", "Generac Holdings Inc."),
    ("AME", "AMETEK Inc."),
    ("ROP", "Roper Technologies Inc."),
    ("IEX", "IDEX Corporation"),
    ("FTV", "Fortive Corporation"),
    ("DHI", "D.R. Horton Inc."),
    ("LEN", "Lennar Corporation"),
    ("PHM", "PulteGroup Inc."),
    ("TOL", "Toll Brothers Inc."),
    ("NVR", "NVR Inc."),
    ("MDC", "M.D.C. Holdings Inc."),
    # Materials
    ("LIN", "Linde plc"),
    ("APD", "Air Products and Chemicals Inc."),
    ("SHW", "Sherwin-Williams Company"),
    ("PPG", "PPG Industries Inc."),
    ("ECL", "Ecolab Inc."),
    ("DD", "DuPont de Nemours Inc."),
    ("DOW", "Dow Inc."),
    ("LYB", "LyondellBasell Industries NV"),
    ("CF", "CF Industries Holdings Inc."),
    ("MOS", "Mosaic Company"),
    ("NUE", "Nucor Corporation"),
    ("STLD", "Steel Dynamics Inc."),
    ("RS", "Reliance Steel & Aluminum Co."),
    ("ALB", "Albemarle Corporation"),
    ("FCX", "Freeport-McMoRan Inc."),
    ("NEM", "Newmont Corporation"),
    ("GOLD", "Barrick Gold Corporation"),
    ("AA", "Alcoa Corporation"),
    ("X", "United States Steel Corp."),
    ("CLF", "Cleveland-Cliffs Inc."),
    # Real Estate & Utilities
    ("AMT", "American Tower Corporation"),
    ("PLD", "Prologis Inc."),
    ("CCI", "Crown Castle Inc."),
    ("EQIX", "Equinix Inc."),
    ("PSA", "Public Storage"),
    ("EXR", "Extra Space Storage Inc."),
    ("WELL", "Welltower Inc."),
    ("VTR", "Ventas Inc."),
    ("AVB", "AvalonBay Communities Inc."),
    ("EQR", "Equity Residential"),
    ("O", "Realty Income Corporation"),
    ("NNN", "NNN REIT Inc."),
    ("SPG", "Simon Property Group Inc."),
    ("MAC", "Macerich Company"),
    ("BXP", "BXP Inc."),
    ("VNO", "Vornado Realty Trust"),
    ("NEE", "NextEra Energy Inc."),
    ("DUK", "Duke Energy Corporation"),
    ("SO", "Southern Company"),
    ("D", "Dominion Energy Inc."),
    ("AEP", "American Electric Power Co."),
    ("EXC", "Exelon Corporation"),
    ("SRE", "Sempra"),
    ("PCG", "PG&E Corporation"),
    ("XEL", "Xcel Energy Inc."),
    ("ED", "Consolidated Edison Inc."),
    ("WEC", "WEC Energy Group Inc."),
    ("ES", "Eversource Energy"),
    ("AWK", "American Water Works Co."),
    ("CMS", "CMS Energy Corporation"),
    # Telecom
    ("T", "AT&T Inc."),
    ("VZ", "Verizon Communications Inc."),
    ("TMUS", "T-Mobile US Inc."),
    ("LUMN", "Lumen Technologies Inc."),
    ("DISH", "DISH Network Corporation"),
    # ETFs
    ("SPY", "SPDR S&P 500 ETF Trust"),
    ("QQQ", "Invesco QQQ Trust"),
    ("IWM", "iShares Russell 2000 ETF"),
    ("DIA", "SPDR Dow Jones Industrial ETF"),
    ("GLD", "SPDR Gold Shares"),
    ("SLV", "iShares Silver Trust"),
    ("USO", "United States Oil Fund"),
    ("XLE", "Energy Select Sector SPDR"),
    ("XLF", "Financial Select Sector SPDR"),
    ("XLK", "Technology Select Sector SPDR"),
    ("XLV", "Health Care Select Sector SPDR"),
    ("XLI", "Industrial Select Sector SPDR"),
    ("XLP", "Consumer Staples Select SPDR"),
    ("XLY", "Consumer Discretionary SPDR"),
    ("XLB", "Materials Select Sector SPDR"),
    ("XLU", "Utilities Select Sector SPDR"),
    ("XLRE", "Real Estate Select Sector SPDR"),
    ("VOO", "Vanguard S&P 500 ETF"),
    ("VTI", "Vanguard Total Stock Market ETF"),
    ("ARKK", "ARK Innovation ETF"),
    # Other popular
    ("BRK.B", "Berkshire Hathaway Inc."),
    ("BRK.A", "Berkshire Hathaway Inc."),
    ("GM", "General Motors Company"),
    ("F", "Ford Motor Company"),
    ("TM", "Toyota Motor Corporation"),
    ("HMC", "Honda Motor Co. Ltd."),
    ("RIVN", "Rivian Automotive Inc."),
    ("LCID", "Lucid Group Inc."),
    ("NIO", "NIO Inc."),
    ("LI", "Li Auto Inc."),
    ("XPEV", "XPeng Inc."),
    ("BABA", "Alibaba Group Holding Ltd."),
    ("JD", "JD.com Inc."),
    ("PDD", "PDD Holdings Inc."),
    ("BIDU", "Baidu Inc."),
    ("TCEHY", "Tencent Holdings Ltd."),
    ("TME", "Tencent Music Entertainment"),
    ("SE", "Sea Limited"),
    ("GRAB", "Grab Holdings Limited"),
    ("SHOP", "Shopify Inc."),
    ("SQ", "Block Inc."),
    ("COIN", "Coinbase Global Inc."),
    ("MSTR", "MicroStrategy Inc."),
    ("HOOD", "Robinhood Markets Inc."),
    ("SOFI", "SoFi Technologies Inc."),
    ("AFRM", "Affirm Holdings Inc."),
    ("UPST", "Upstart Holdings Inc."),
    ("OPEN", "Opendoor Technologies Inc."),
    ("Z", "Zillow Group Inc."),
    ("RDFN", "Redfin Corporation"),
    ("W", "Wayfair Inc."),
    ("ETSY", "Etsy Inc."),
    ("EBAY", "eBay Inc."),
    ("PINS", "Pinterest Inc."),
    ("SNAP", "Snap Inc."),
    ("TWTR", "Twitter / X Corp"),
    ("RDDT", "Reddit Inc."),
    ("DUOL", "Duolingo Inc."),
    ("COUR", "Coursera Inc."),
    ("ZM", "Zoom Video Communications"),
    ("DOCU", "DocuSign Inc."),
    ("BOX", "Box Inc."),
    ("TWLO", "Twilio Inc."),
    ("SEND", "SendGrid (Twilio)"),
    ("HCP", "HashiCorp Inc."),
    ("GTLB", "GitLab Inc."),
    ("PATH", "UiPath Inc."),
    ("AI", "C3.ai Inc."),
    ("BBAI", "BigBear.ai Holdings Inc."),
    ("SOUN", "SoundHound AI Inc."),
    ("IREN", "Iris Energy Limited"),
    ("RIOT", "Riot Platforms Inc."),
    ("MARA", "MARA Holdings Inc."),
    ("HUT", "Hut 8 Corp."),
    ("CLSK", "CleanSpark Inc."),
    ("WULF", "TeraWulf Inc."),
    ("CIFR", "Cipher Mining Inc."),
    ("BTBT", "Bit Digital Inc."),
    ("IBM", "International Business Machines"),
    ("HPQ", "HP Inc."),
    ("HPE", "Hewlett Packard Enterprise"),
    ("DELL", "Dell Technologies Inc."),
    ("NTAP", "NetApp Inc."),
    ("PSTG", "Pure Storage Inc."),
    ("NTNX", "Nutanix Inc."),
    ("VMW", "VMware Inc."),
    ("ACN", "Accenture plc"),
    ("CTSH", "Cognizant Technology Solutions"),
    ("WIT", "Wipro Limited"),
    ("INFY", "Infosys Limited"),
    ("HCL", "HCL Technologies Ltd."),
    ("TCS", "Tata Consultancy Services"),
    ("SAP", "SAP SE"),
    ("ASML", "ASML Holding NV"),
    ("TSM", "Taiwan Semiconductor Mfg."),
    ("SONY", "Sony Group Corporation"),
    ("SNE", "Sony Group Corporation"),
    ("ERIC", "Telefonaktiebolaget LM Ericsson"),
    ("NOK", "Nokia Corporation"),
    ("BBRY", "BlackBerry Limited"),
    ("BB", "BlackBerry Limited"),
]

IN_STOCKS = [
    # Nifty 50
    ("RELIANCE", "Reliance Industries Ltd."),
    ("TCS", "Tata Consultancy Services Ltd."),
    ("HDFCBANK", "HDFC Bank Ltd."),
    ("BHARTIARTL", "Bharti Airtel Ltd."),
    ("ICICIBANK", "ICICI Bank Ltd."),
    ("INFOSYS", "Infosys Ltd."),
    ("INFY", "Infosys Ltd."),
    ("SBIN", "State Bank of India"),
    ("HINDUNILVR", "Hindustan Unilever Ltd."),
    ("ITC", "ITC Ltd."),
    ("LT", "Larsen & Toubro Ltd."),
    ("HCLTECH", "HCL Technologies Ltd."),
    ("BAJFINANCE", "Bajaj Finance Ltd."),
    ("SUNPHARMA", "Sun Pharmaceutical Industries"),
    ("MARUTI", "Maruti Suzuki India Ltd."),
    ("KOTAKBANK", "Kotak Mahindra Bank Ltd."),
    ("AXISBANK", "Axis Bank Ltd."),
    ("ASIANPAINT", "Asian Paints Ltd."),
    ("NESTLEIND", "Nestle India Ltd."),
    ("TITAN", "Titan Company Ltd."),
    ("WIPRO", "Wipro Ltd."),
    ("ULTRACEMCO", "UltraTech Cement Ltd."),
    ("ADANIENT", "Adani Enterprises Ltd."),
    ("ADANIPORTS", "Adani Ports & SEZ Ltd."),
    ("POWERGRID", "Power Grid Corporation of India"),
    ("NTPC", "NTPC Ltd."),
    ("ONGC", "Oil & Natural Gas Corporation"),
    ("COALINDIA", "Coal India Ltd."),
    ("BAJAJFINSV", "Bajaj Finserv Ltd."),
    ("TECHM", "Tech Mahindra Ltd."),
    ("M&M", "Mahindra & Mahindra Ltd."),
    ("TATAMOTORS", "Tata Motors Ltd."),
    ("TATASTEEL", "Tata Steel Ltd."),
    ("JSWSTEEL", "JSW Steel Ltd."),
    ("HINDALCO", "Hindalco Industries Ltd."),
    ("DRREDDY", "Dr. Reddy's Laboratories"),
    ("CIPLA", "Cipla Ltd."),
    ("DIVISLAB", "Divi's Laboratories Ltd."),
    ("APOLLOHOSP", "Apollo Hospitals Enterprise"),
    ("EICHERMOT", "Eicher Motors Ltd."),
    ("HEROMOTOCO", "Hero MotoCorp Ltd."),
    ("BAJAJ-AUTO", "Bajaj Auto Ltd."),
    ("BPCL", "Bharat Petroleum Corp. Ltd."),
    ("IOC", "Indian Oil Corporation Ltd."),
    ("GRASIM", "Grasim Industries Ltd."),
    ("INDUSINDBK", "IndusInd Bank Ltd."),
    ("BRITANNIA", "Britannia Industries Ltd."),
    ("TATACONSUM", "Tata Consumer Products Ltd."),
    ("UPL", "UPL Ltd."),
    ("SHRIRAMFIN", "Shriram Finance Ltd."),
    # Nifty Next 50
    ("SIEMENS", "Siemens Ltd."),
    ("HAVELLS", "Havells India Ltd."),
    ("PIDILITIND", "Pidilite Industries Ltd."),
    ("BERGEPAINT", "Berger Paints India Ltd."),
    ("WHIRLPOOL", "Whirlpool of India Ltd."),
    ("VOLTAS", "Voltas Ltd."),
    ("BLUESTARCO", "Blue Star Ltd."),
    ("CROMPTON", "Crompton Greaves Consumer Elec."),
    ("RAJESHEXPO", "Rajesh Exports Ltd."),
    ("MUTHOOTFIN", "Muthoot Finance Ltd."),
    ("CHOLAFIN", "Cholamandalam Investment & Fin."),
    ("BAJAJHLDNG", "Bajaj Holdings & Investments"),
    ("SBILIFE", "SBI Life Insurance Company"),
    ("HDFCLIFE", "HDFC Life Insurance Company"),
    ("ICICIPRULI", "ICICI Prudential Life Insurance"),
    ("ICICIGI", "ICICI Lombard General Insurance"),
    ("SBICARD", "SBI Cards and Payment Services"),
    ("NAUKRI", "Info Edge (India) Ltd."),
    ("ZOMATO", "Zomato Ltd."),
    ("SWIGGY", "Swiggy Ltd."),
    ("PAYTM", "One97 Communications Ltd."),
    ("POLICYBZR", "PB Fintech Ltd."),
    ("DELHIVERY", "Delhivery Ltd."),
    ("NYKAA", "FSN E-Commerce Ventures Ltd."),
    ("CARTRADE", "CarTrade Tech Ltd."),
    ("INDIAMART", "IndiaMART InterMESH Ltd."),
    ("AFFLE", "Affle (India) Ltd."),
    ("MAPMYINDIA", "C.E. Info Systems Ltd."),
    ("HAPPSTMNDS", "Happiest Minds Technologies"),
    ("LTIM", "LTIMindtree Ltd."),
    ("LTTS", "L&T Technology Services Ltd."),
    ("PERSISTENT", "Persistent Systems Ltd."),
    ("COFORGE", "Coforge Ltd."),
    ("MPHASIS", "Mphasis Ltd."),
    ("OFSS", "Oracle Financial Services Software"),
    ("KPITTECH", "KPIT Technologies Ltd."),
    ("CYIENT", "Cyient Ltd."),
    ("TATAELXSI", "Tata Elxsi Ltd."),
    ("ZENSAR", "Zensar Technologies Ltd."),
    ("HEXAWARE", "Hexaware Technologies Ltd."),
    ("MASTEK", "Mastek Ltd."),
    ("RATEGAIN", "RateGain Travel Technologies"),
    ("TANLA", "Tanla Platforms Ltd."),
    ("NEWGEN", "Newgen Software Technologies"),
    # Banking & Finance
    ("PNB", "Punjab National Bank"),
    ("BANKBARODA", "Bank of Baroda"),
    ("CANARABANK", "Canara Bank"),
    ("UNIONBANK", "Union Bank of India"),
    ("IDFCFIRSTB", "IDFC First Bank Ltd."),
    ("FEDERALBNK", "Federal Bank Ltd."),
    ("BANDHANBNK", "Bandhan Bank Ltd."),
    ("RBLBANK", "RBL Bank Ltd."),
    ("YESBANK", "Yes Bank Ltd."),
    ("KARURVYSYA", "Karur Vysya Bank Ltd."),
    ("DCBBANK", "DCB Bank Ltd."),
    ("CSBBANK", "CSB Bank Ltd."),
    ("SOUTHBANK", "South Indian Bank Ltd."),
    ("EQUITASBNK", "Equitas Small Finance Bank"),
    ("UJJIVANSFB", "Ujjivan Small Finance Bank"),
    ("AUBANK", "AU Small Finance Bank Ltd."),
    ("SURYODAY", "Suryoday Small Finance Bank"),
    ("ESAFSFB", "ESAF Small Finance Bank"),
    ("FINPIPE", "Finolex Industries Ltd."),
    ("MANAPPURAM", "Manappuram Finance Ltd."),
    ("IIFL", "IIFL Finance Ltd."),
    ("AARTIIND", "Aarti Industries Ltd."),
    ("M&MFIN", "Mahindra & Mahindra Financial"),
    ("SUNDARMFIN", "Sundaram Finance Ltd."),
    ("L&TFH", "L&T Finance Holdings Ltd."),
    ("PNBHOUSING", "PNB Housing Finance Ltd."),
    ("LICHSGFIN", "LIC Housing Finance Ltd."),
    ("CANFINHOME", "Can Fin Homes Ltd."),
    ("HOMEFIRST", "Home First Finance Company"),
    ("AAVAS", "Aavas Financiers Ltd."),
    ("REPCO", "Repco Home Finance Ltd."),
    # Auto & Auto Ancillary
    ("ASHOKLEY", "Ashok Leyland Ltd."),
    ("TVSMOTOR", "TVS Motor Company Ltd."),
    ("ESCORTS", "Escorts Kubota Ltd."),
    ("FORCEMOT", "Force Motors Ltd."),
    ("SML", "SML Isuzu Ltd."),
    ("MOTHERSON", "Samvardhana Motherson Intl."),
    ("BOSCHLTD", "Bosch Ltd."),
    ("BHARAT FORGE", "Bharat Forge Ltd."),
    ("BHARATFORG", "Bharat Forge Ltd."),
    ("EXIDEIND", "Exide Industries Ltd."),
    ("AMARARAJA", "Amara Raja Energy & Mobility"),
    ("APOLLOTYRE", "Apollo Tyres Ltd."),
    ("CEATLTD", "CEAT Ltd."),
    ("MRF", "MRF Ltd."),
    ("BALKRISIND", "Balkrishna Industries Ltd."),
    ("ENDURANCE", "Endurance Technologies Ltd."),
    ("SUPRAJIT", "Suprajit Engineering Ltd."),
    ("LUMAX", "Lumax Industries Ltd."),
    ("SUNDRMFAST", "Sundram Fasteners Ltd."),
    ("GABRIEL", "Gabriel India Ltd."),
    ("MINDA", "Minda Industries Ltd."),
    ("CRAFTSMAN", "Craftsman Automation Ltd."),
    ("SANSERA", "Sansera Engineering Ltd."),
    # Pharma & Healthcare
    ("AUROPHARMA", "Aurobindo Pharma Ltd."),
    ("LUPIN", "Lupin Ltd."),
    ("TORNTPHARM", "Torrent Pharmaceuticals Ltd."),
    ("ALKEM", "Alkem Laboratories Ltd."),
    ("GLAXO", "GlaxoSmithKline Pharmaceuticals"),
    ("PFIZER", "Pfizer Ltd."),
    ("ABBOTINDIA", "Abbott India Ltd."),
    ("SANOFI", "Sanofi India Ltd."),
    ("IPCALAB", "IPCA Laboratories Ltd."),
    ("NATCOPHARM", "Natco Pharma Ltd."),
    ("GRANULES", "Granules India Ltd."),
    ("AJANTPHARM", "Ajanta Pharma Ltd."),
    ("JBCHEPHARM", "JB Chemicals & Pharmaceuticals"),
    ("MANKIND", "Mankind Pharma Ltd."),
    ("GLENMARK", "Glenmark Pharmaceuticals Ltd."),
    ("BIOCON", "Biocon Ltd."),
    ("LALPATHLAB", "Dr. Lal PathLabs Ltd."),
    ("METROPOLIS", "Metropolis Healthcare Ltd."),
    ("KRSNAA", "Krsnaa Diagnostics Ltd."),
    ("THYROCARE", "Thyrocare Technologies Ltd."),
    ("MAXHEALTH", "Max Healthcare Institute Ltd."),
    ("FORTIS", "Fortis Healthcare Ltd."),
    ("NARAYANHRU", "Narayana Hrudayalaya Ltd."),
    ("RAINBOW", "Rainbow Children Medicare Ltd."),
    ("MEDANTA", "Global Health Ltd."),
    # FMCG & Retail
    ("EMAMILTD", "Emami Ltd."),
    ("MARICO", "Marico Ltd."),
    ("DABUR", "Dabur India Ltd."),
    ("GODREJCP", "Godrej Consumer Products Ltd."),
    ("COLPAL", "Colgate-Palmolive (India) Ltd."),
    ("PGHH", "Procter & Gamble Hygiene"),
    ("GILLETTE", "Gillette India Ltd."),
    ("JYOTHYLAB", "Jyothy Labs Ltd."),
    ("BAJAJCON", "Bajaj Consumer Care Ltd."),
    ("KPRMILL", "K.P.R. Mill Ltd."),
    ("PAGEIND", "Page Industries Ltd."),
    ("KHADIM", "Khadim India Ltd."),
    ("BATA", "Bata India Ltd."),
    ("RELAXO", "Relaxo Footwears Ltd."),
    ("METRO", "Metro Brands Ltd."),
    ("CAMPUS", "Campus Activewear Ltd."),
    ("DMART", "Avenue Supermarts Ltd."),
    ("VSTIND", "VST Industries Ltd."),
    ("GODFRYPHLP", "Godfrey Phillips India Ltd."),
    ("VBL", "Varun Beverages Ltd."),
    ("RADICO", "Radico Khaitan Ltd."),
    ("UNITEDSPRT", "United Spirits Ltd."),
    ("MCDOWELL-N", "United Spirits Ltd."),
    ("UBL", "United Breweries Ltd."),
    # Cement & Infrastructure
    ("AMBUJACEM", "Ambuja Cements Ltd."),
    ("ACCLTD", "ACC Ltd."),
    ("RAMCOCEM", "Ramco Cements Ltd."),
    ("JKCEMENT", "JK Cement Ltd."),
    ("HEIDELBERG", "HeidelbergCement India Ltd."),
    ("SHREECEM", "Shree Cement Ltd."),
    ("STARCEMENT", "Star Cement Ltd."),
    ("NUVOCO", "Nuvoco Vistas Corporation Ltd."),
    ("DLF", "DLF Ltd."),
    ("GODREJPROP", "Godrej Properties Ltd."),
    ("OBEROIRLTY", "Oberoi Realty Ltd."),
    ("PRESTIGE", "Prestige Estates Projects Ltd."),
    ("BRIGADE", "Brigade Enterprises Ltd."),
    ("MAHLIFE", "Mahindra Lifespace Developers"),
    ("SOBHA", "Sobha Ltd."),
    ("PHOENIXLTD", "Phoenix Mills Ltd."),
    ("SUNTECK", "Sunteck Realty Ltd."),
    ("KOLTEPATIL", "Kolte-Patil Developers Ltd."),
    ("ARVIND", "Arvind Ltd."),
    ("ASHIANA", "Ashiana Housing Ltd."),
    ("NCC", "NCC Ltd."),
    ("KEC", "KEC International Ltd."),
    ("KALPATPOWR", "Kalpataru Projects Intl. Ltd."),
    ("PNCINFRA", "PNC Infratech Ltd."),
    ("IRB", "IRB Infrastructure Developers"),
    ("SADBHAV", "Sadbhav Engineering Ltd."),
    ("HGINFRA", "H.G. Infra Engineering Ltd."),
    ("GPPL", "Gujarat Pipavav Port Ltd."),
    ("ADANIGREEN", "Adani Green Energy Ltd."),
    ("ADANITRANS", "Adani Transmission Ltd."),
    ("ADANIPOWER", "Adani Power Ltd."),
    ("ATGL", "Adani Total Gas Ltd."),
    # Power & Energy
    ("TATAPOWER", "Tata Power Company Ltd."),
    ("TORNTPOWER", "Torrent Power Ltd."),
    ("CESC", "CESC Ltd."),
    ("JSPL", "Jindal Steel & Power Ltd."),
    ("JSWENERGY", "JSW Energy Ltd."),
    ("INOXWIND", "Inox Wind Ltd."),
    ("SUZLON", "Suzlon Energy Ltd."),
    ("ORIENTGRN", "Orient Green Power Company"),
    ("RENUKA", "Shree Renuka Sugars Ltd."),
    ("RPOWER", "Reliance Power Ltd."),
    ("NHPC", "NHPC Ltd."),
    ("SJVN", "SJVN Ltd."),
    ("RECLTD", "REC Ltd."),
    ("PFC", "Power Finance Corporation Ltd."),
    ("IRFC", "Indian Railway Finance Corp."),
    ("IRCON", "Ircon International Ltd."),
    ("RVNL", "Rail Vikas Nigam Ltd."),
    ("RAILTEL", "RailTel Corporation of India"),
    ("IRCTC", "Indian Railway Catering & Tourism"),
    # Metals & Mining
    ("VEDL", "Vedanta Ltd."),
    ("HINDZINC", "Hindustan Zinc Ltd."),
    ("NMDC", "NMDC Ltd."),
    ("MOIL", "MOIL Ltd."),
    ("NATIONALUM", "National Aluminium Company"),
    ("SAIL", "Steel Authority of India Ltd."),
    ("JINDALSAW", "Jindal Saw Ltd."),
    ("WELSPUNIND", "Welspun India Ltd."),
    ("APLAPOLLO", "APL Apollo Tubes Ltd."),
    ("RATNAMANI", "Ratnamani Metals & Tubes Ltd."),
    ("ISMT", "ISMT Ltd."),
    ("NILE", "Nile Ltd."),
    ("GMRINFRA", "GMR Airports Infrastructure"),
    # Chemicals & Fertilisers
    ("PIDILITE", "Pidilite Industries Ltd."),
    ("AARTIIND", "Aarti Industries Ltd."),
    ("TATACHEM", "Tata Chemicals Ltd."),
    ("DEEPAKNITR", "Deepak Nitrite Ltd."),
    ("NAVINFLUOR", "Navin Fluorine International"),
    ("FLUOROCHEM", "Gujarat Fluorochemicals Ltd."),
    ("ALKYLAMINE", "Alkyl Amines Chemicals Ltd."),
    ("BALCHEMIND", "Balaji Amines Ltd."),
    ("CLEAN", "Clean Science & Technology"),
    ("NOCIL", "NOCIL Ltd."),
    ("GALLANTT", "Gallantt Ispat Ltd."),
    ("SRF", "SRF Ltd."),
    ("SUDARSCHEM", "Sudarshan Chemical Industries"),
    ("VINDHYATEL", "Vindhya Telelinks Ltd."),
    ("COROMANDEL", "Coromandel International Ltd."),
    ("CHAMBLFERT", "Chambal Fertilisers & Chemicals"),
    ("GSFC", "Gujarat State Fertilizers & Chem."),
    ("NFL", "National Fertilizers Ltd."),
    ("RCF", "Rashtriya Chemicals & Fertilizers"),
    ("GNFC", "Gujarat Narmada Valley Fertilizers"),
    # Textiles
    ("VARDHMAN", "Vardhman Textiles Ltd."),
    ("RAYMOND", "Raymond Ltd."),
    ("ARVINDLTD", "Arvind Ltd."),
    ("TRIDENT", "Trident Ltd."),
    ("WELSPUN", "Welspun Living Ltd."),
    ("GOKEX", "Gokaldas Exports Ltd."),
    ("KITEX", "Kitex Garments Ltd."),
    ("SPENCERS", "Spencer's Retail Ltd."),
    ("SHOPERSTOP", "Shoppers Stop Ltd."),
    ("TRENT", "Trent Ltd."),
    ("VSTIL", "V.S.T. Tillers Tractors Ltd."),
    # Telecom & Media
    ("IDEA", "Vodafone Idea Ltd."),
    ("TATACOMM", "Tata Communications Ltd."),
    ("HFCL", "HFCL Ltd."),
    ("STLTECH", "Sterlite Technologies Ltd."),
    ("TEJASNET", "Tejas Networks Ltd."),
    ("NETWORK18", "Network18 Media & Investments"),
    ("TV18BRDCST", "TV18 Broadcast Ltd."),
    ("ZEEL", "Zee Entertainment Enterprises"),
    ("SUNTV", "Sun TV Network Ltd."),
    ("PVR", "PVR INOX Ltd."),
    ("PVRINOX", "PVR INOX Ltd."),
    ("INOXLEISUR", "PVR INOX Ltd."),
    ("SAREGAMA", "Saregama India Ltd."),
    ("TIPS", "TIPS Music Ltd."),
    # Aviation & Logistics
    ("INDIGO", "InterGlobe Aviation Ltd."),
    ("SPICEJET", "SpiceJet Ltd."),
    ("BLUEDART", "Blue Dart Express Ltd."),
    ("MAHLOG", "Mahindra Logistics Ltd."),
    ("GATI", "Gati Ltd."),
    ("TCI", "Transport Corporation of India"),
    ("ALLCARGO", "Allcargo Logistics Ltd."),
    ("CONCOR", "Container Corporation of India"),
    ("VRL", "VRL Logistics Ltd."),
    # Consumer Durables & Electronics
    ("DIXON", "Dixon Technologies (India) Ltd."),
    ("AMBER", "Amber Enterprises India Ltd."),
    ("WHIRLPOOL", "Whirlpool of India Ltd."),
    ("VGUARD", "V-Guard Industries Ltd."),
    ("ORIENTELEC", "Orient Electric Ltd."),
    ("BAJAJELEC", "Bajaj Electricals Ltd."),
    ("SYMPHONY", "Symphony Ltd."),
    ("TTK PRESTIGE", "TTK Prestige Ltd."),
    ("TTKPRESTIG", "TTK Prestige Ltd."),
    ("HAWKINCOOK", "Hawkins Cookers Ltd."),
    ("STOVEKRAFT", "Stove Kraft Ltd."),
    ("POLICYBZR", "PB Fintech Ltd."),
    # Agri & Food
    ("AVANTIFEED", "Avanti Feeds Ltd."),
    ("ZYDUSWELL", "Zydus Wellness Ltd."),
    ("HATSUN", "Hatsun Agro Product Ltd."),
    ("PARAG", "Parag Milk Foods Ltd."),
    ("HERITAGE", "Heritage Foods Ltd."),
    ("KWALITY", "Kwality Ltd."),
    ("PRABHAT", "Prabhat Dairy Ltd."),
    ("KRBL", "KRBL Ltd."),
    ("LT FOODS", "LT Foods Ltd."),
    ("LTFOODS", "LT Foods Ltd."),
    ("USHAMART", "Usha Martin Ltd."),
    # Indices (for reference)
    ("NIFTY50", "Nifty 50 Index"),
    ("SENSEX", "BSE Sensex Index"),
    ("BANKNIFTY", "Nifty Bank Index"),
    ("NIFTYMIDCAP", "Nifty Midcap 100 Index"),
    ("NIFTYIT", "Nifty IT Index"),
]

CRYPTO_COINS = [
    ("BTC", "Bitcoin"),
    ("ETH", "Ethereum"),
    ("BNB", "BNB"),
    ("SOL", "Solana"),
    ("XRP", "XRP"),
    ("ADA", "Cardano"),
    ("DOGE", "Dogecoin"),
    ("AVAX", "Avalanche"),
    ("LINK", "Chainlink"),
    ("DOT", "Polkadot"),
    ("MATIC", "Polygon"),
    ("UNI", "Uniswap"),
    ("LTC", "Litecoin"),
    ("ATOM", "Cosmos"),
    ("NEAR", "NEAR Protocol"),
    ("APT", "Aptos"),
    ("ARB", "Arbitrum"),
    ("OP", "Optimism"),
    ("FTM", "Fantom"),
    ("ALGO", "Algorand"),
    ("VET", "VeChain"),
    ("SAND", "The Sandbox"),
    ("MANA", "Decentraland"),
    ("AXS", "Axie Infinity"),
    ("CRO", "Cronos"),
    ("SHIB", "Shiba Inu"),
    ("PEPE", "Pepe"),
    ("FLOKI", "Floki"),
    ("WIF", "Dogwifhat"),
    ("BONK", "Bonk"),
]


def search_universe(query: str, market: str, limit: int = 8) -> list:
    q = query.lower().strip()
    results = []

    sources = []
    if market in ("US", "ALL"):
        sources.append(("US", US_STOCKS))
    if market in ("IN", "ALL"):
        sources.append(("IN", IN_STOCKS))
    if market in ("CRYPTO", "ALL"):
        sources.append(("CRYPTO", CRYPTO_COINS))

    seen = set()
    for mkt, stocks in sources:
        for sym, name in stocks:
            if sym in seen:
                continue
            # match if query appears in symbol OR name (case-insensitive)
            if q in sym.lower() or q in name.lower():
                seen.add(sym)
                suffix = ".NS" if mkt == "IN" else ""
                results.append({
                    "symbol": sym + suffix,
                    "name": name,
                    "market": mkt,
                })
                if len(results) >= limit:
                    return results

    return results
